# Pandas Exercises

In [7]:
import pandas as pd

url = "https://raw.githubusercontent.com/BeaverWorksMedlytics2020/Data_Public/master/NotebookExampleData/Week1/diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
"""
      'preg': number of pregnancies
      'plas': plasma glucose concentration
      'pres': blood pressure
      'skin': skin thickness
      'test': Insluin
      'mass': BMI
      'pedi': diabetes pedigree function
      'age': age
      'class': '0' means does not have diabetes and '1' means has diabetes
"""

"\n      'preg': number of pregnancies  \n      'plas': plasma glucose concentration \n      'pres': blood pressure \n      'skin': skin thickness\n      'test': Insluin\n      'mass': BMI\n      'pedi': diabetes pedigree function\n      'age': age\n      'class': '0' means does not have diabetes and '1' means has diabetes\n"

Read in csv above to a pandas dataframe

In [8]:
# YOUR CODE HERE
data = pd.read_csv(url, names=names)

Print out the age and class of the 100th patient

In [9]:
# YOUR CODE HERE
print(data.loc[99, 'age']), print(data.loc[99, 'class'])

31
1

(None, None)

Write code to figure out how many people are classified as not having diabetes, class is 0

In [10]:
# YOUR CODE HERE
print(data.loc[data['class'] == 0].shape[0])

500

Write code to figure out how many people are classified as having diabetes, class is 1

In [11]:
# YOUR CODE HERE
print(data.loc[data['class'] == 1].shape[0])

268

What percent of people have diabetes in the study

In [12]:
# YOUR CODE HERE
print(data.loc[data['class'] == 1].shape[0] / data.shape[0])

0.3489583333333333

Print out the `"pres"` and `"class"` (no other columns) for the first 5 people

In [13]:
# YOUR CODE HERE
print(data.loc[0:4, ['pres', 'class']])

   pres  class
0    72      1
1    66      0
2    64      1
3    66      0
4    40      1

Run the cell below, it will print out the correlation among the columns

In [14]:
df=data
data.corr()

,preg,plas,pres,skin,test,mass,pedi,age,class
preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
plas,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
pres,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
test,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
mass,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
pedi,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
class,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

What column has the highest correlation with class? Find the mean() value of that column

In [15]:
# YOUR CODE HERE
print(data.corr()['class'].idxmax())
print(data['mass'].mean())

class
31.992578124999998

Create a new dataframe with only people that are above the mean found in the above cell.

In [16]:
# YOUR CODE HERE
new_data = data.loc[data['mass'] > data['mass'].mean()]
print(new_data)

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
4       0   137    40    35   168  43.1  2.288   33      1
7      10   115     0     0     0  35.3  0.134   29      0
10      4   110    92     0     0  37.6  0.191   30      0
11     10   168    74     0     0  38.0  0.537   34      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
758     1   106    76     0     0  37.5  0.197   26      0
759     6   190    92     0     0  35.5  0.278   66      1
761     9   170    74    31     0  44.0  0.403   43      1
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0

[395 rows x 9 columns]

Create a new dataframe that only includes people who are above the average value for each column in the dataset. In other words, find the average value for each column, and then find which users have values above all of these average column values.

In [17]:
# YOUR CODE HERE
new_df_all = data[(data > data.mean()).all(axis=1)]
print(new_df_all)

     preg  plas  pres  skin  test  mass   pedi  age  class
43      9   171   110    24   240  45.4  0.721   54      1
152     9   156    86    28   155  34.3  1.189   42      1
159    17   163    72    41   114  40.9  0.817   47      1
175     8   179    72    42   130  32.7  0.719   36      1
206     8   196    76    29   280  37.5  0.605   57      1
215    12   151    70    40   271  41.8  0.742   38      1
236     7   181    84    21   192  35.9  0.586   51      1
259    11   155    76    28   150  33.3  1.353   51      1
375    12   140    82    43   325  39.2  0.528   58      1
424     8   151    78    32   210  42.9  0.516   36      1
458    10   148    84    48   237  37.6  1.001   51      1
546     5   187    76    27   207  43.6  1.034   53      1
603     7   150    78    29   126  35.2  0.692   54      1
612     7   168    88    42   321  38.2  0.787   40      1
614    11   138    74    26   144  36.1  0.557   50      1
663     9   145    80    46   130  37.9  0.637   40      1

*Note: the next 3 problems were not explicitly shown in our tutorial—being able to effectively google and look through documentation is a very important coding tool!* ¯\\\_(ツ)_/¯

Ignoring the index (resetting the index to 0) and using the dataframe from the cell above, sort the values based on `"skin"`, `"test"`, and `"pedi"` values in ascending order. Please write this in one line.

In [18]:
# YOUR CODE HERE
new_df_all.reset_index(drop=True).sort_values(by=['skin', 'test', 'pedi'])

    preg  plas  pres  skin  test  mass   pedi  age  class
6      7   181    84    21   192  35.9  0.586   51      1
0      9   171   110    24   240  45.4  0.721   54      1
14    11   138    74    26   144  36.1  0.557   50      1
11     5   187    76    27   207  43.6  1.034   53      1
7     11   155    76    28   150  33.3  1.353   51      1
1      9   156    86    28   155  34.3  1.189   42      1
12     7   150    78    29   126  35.2  0.692   54      1
4      8   196    76    29   280  37.5  0.605   57      1
9      8   151    78    32   210  42.9  0.516   36      1
5     12   151    70    40   271  41.8  0.742   38      1
2     17   163    72    41   114  40.9  0.817   47      1
3      8   179    72    42   130  32.7  0.719   36      1
13     7   168    88    42   321  38.2  0.787   40      1
8     12   140    82    43   325  39.2  0.528   58      1
15     9   145    80    46   130  37.9  0.637   40      1
10    10   148    84    48   237  37.6  1.001   51      1

Now let's find the 4 largest values for `"age"`

In [22]:
# YOUR CODE HERE
print(data.nlargest(4, 'age'))

     preg  plas  pres  skin  test  mass   pedi  age  class
459     9   134    74    33    60  25.9  0.460   81      0
453     2   119     0     0     0  19.6  0.832   72      0
666     4   145    82    18     0  32.5  0.235   70      1
123     5   132    80     0     0  26.8  0.186   69      0

Now find the smallest 4 values for `"pedi"` and `"plas"` in reverse order (smallest to largest).

In [24]:
# YOUR CODE HERE
data.nsmallest(4, ['pedi', 'plas']).sort_values(by=['pedi', 'plas'], ascending=False)

     preg  plas  pres  skin  test  mass   pedi  age  class
567     6    92    62    32   126  32.0  0.085   46      0
149     2    90    70    17     0  27.3  0.085   22      0
180     6    87    80     0     0  23.2  0.084   32      0
268     0   102    52     0     0  25.1  0.078   21      0